service: ${self:custom.appName}

provider:
  name: aws
  region: ${opt:region}
  stage: ${opt:stage}
  profile: ${opt:profile}
  deploymentBucket: ${self:custom.appNameFull}-deploys

plugins:
  - serverless-s3-sync
custom:
  appName: serverless-frontend
  appNameFull: ${self:custom.appName}-${self:provider.stage}
  s3Sync:
    - bucketName: ${self:custom.appNameFull}
      localDir: build

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.appNameFull}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticSite"
                    },
                    "/*"
                  ]
                ]
